force-app/main/default/objects/Connected_Org__c/Connected_Org__c.object-meta.xml
<CustomObject>
    <label>Connected Org</label>
    <nameField>
        <label>Connected Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Connected Orgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Connected_Org__c/fields/Admin_User_Name__c.field-meta.xml
<CustomField>
    <fullName>Admin_User_Name__c</fullName>
    <externalId>true</externalId>
    <label>Admin User Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Connected_Org__c/fields/Admin_User_Password__c.field-meta.xml
<CustomField>
    <fullName>Admin_User_Password__c</fullName>
    <label>Admin User Password</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Connected_Org__c/fields/Connected_App_Id__c.field-meta.xml
<CustomField>
    <fullName>Connected_App_Id__c</fullName>
    <label>Connected App Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Connected_Org__c/fields/Github_Repo__c.field-meta.xml
<CustomField>
    <fullName>Github_Repo__c</fullName>
    <label>Github Repo</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Connected_Org__c/fields/IdP_Initiated_Login_URL__c.field-meta.xml
<CustomField>
    <fullName>IdP_Initiated_Login_URL__c</fullName>
    <formula>&quot;https://orgfarm-agentforcemainorg-dev-ed.develop.my.salesforce.com/idp/login?app=&quot; &amp; Connected_App_Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IdP Initiated Login URL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Connected_Org__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Connected_Org__c/fields/Last_Login_Status__c.field-meta.xml
<CustomField>
    <fullName>Last_Login_Status__c</fullName>
    <label>Last Login Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Connected_Org__c/fields/Last_Login_Time__c.field-meta.xml
<CustomField>
    <fullName>Last_Login_Time__c</fullName>
    <label>Last Login Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Connected_Org__c/fields/Login_URL__c.field-meta.xml
<CustomField>
    <fullName>Login_URL__c</fullName>
    <label>Login URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Connected_Org__c/fields/Org_Icon__c.field-meta.xml
<CustomField>
    <fullName>Org_Icon__c</fullName>
    <label>Org Icon</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>custom:custom17</fullName>
                <default>true</default>
                <label>custom:custom17</label>
            </value>
            <value>
                <fullName>custom:custom9</fullName>
            </value>
            <value>
                <fullName>standard:campaign</fullName>
            </value>
            <value>
                <fullName>utility:animal_and_nature</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Connected_Org__c/fields/SSO_Enabled__c.field-meta.xml
<CustomField>
    <fullName>SSO_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SSO Enabled?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/OrgSwitcherController.cls
public with sharing class OrgSwitcherController {
    
    /**
     * Retrieves data with caching enabled for improved performance.
     */
    @AuraEnabled(cacheable=true)
    public static List<Connected_Org__c> getAvailableOrgs(String filterBy, String orderBy) {
        try {

            // Use Database.query to dynamically sort by the provided field
            String query = 'SELECT ' +
                'Id, Name, Admin_User_Name__c, Admin_User_Password__c, ' +
                'IsActive__c, Connected_App_Id__c, ' +
                'Last_Login_Status__c, Org_Icon__c, ' +
                'IdP_Initiated_Login_URL__c, Last_Login_Time__c, ' +
                'Login_URL__c, SSO_Enabled__c, Github_Repo__c ' +
                'FROM Connected_Org__c ' +
                getWhereClause(filterBy) + 
                getOrderByClause(orderBy);
            System.debug('Query: ' + query);    
            return Database.query(query);
        } 
        catch (Exception ex) {
            // Log the exception and throw a user-friendly error
            System.debug('Error fetching connected orgs: ' + ex.getMessage());
            throw new AuraHandledException('Unable to fetch connected orgs. Please try again later.');
        }
    }


	private static String getOrderByClause(String orderBy){
        // Construct the ORDER BY clause based on the `orderBy` parameter
        String orderByClause = '';
        if (orderBy == 'Name') {
            orderByClause = ' ORDER BY Name ASC';
        } 
        else if (orderBy == 'Last_Login') {
            orderByClause = ' ORDER BY Last_Login_Time__c DESC';
        } 
        else {
            orderByClause = '';
        }
        return orderByClause;
	} 

    // Construct the WHERE clause based on the `filterBy` parameter
    private static String getWhereClause(String filterBy){
        String whereClause = '';
        if (filterBy == 'All') {
            whereClause = '';
        } 
        else if (filterBy == 'Active_Orgs') {
            whereClause = ' WHERE IsActive__c = true ';
        }
        else if (filterBy == 'Inactive_Orgs') {
            whereClause = ' WHERE IsActive__c = false ';
        } 
        else if (filterBy == 'SSO_Enabled') {
            whereClause = ' WHERE SSO_Enabled__c = true ';
        }
        else if (filterBy == 'SSO_Disabled') {
            whereClause = ' WHERE SSO_Enabled__c = false ';
        }
        else if (filterBy == 'Orgs_Not_Logged_In_Last_30_Days') {
            DateTime last30Days = DateTime.now().addDays(-30);
            String last30DaysString = last30Days.format('yyyy-MM-dd\'T\'HH:mm:ss.SSS\'Z\'');
            whereClause = ' WHERE Last_Login_Time__c = null OR Last_Login_Time__c < ' + last30DaysString;
        }
        return whereClause;
    }
}